import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
!pip install mplsoccer

Collecting mplsoccer
  Downloading mplsoccer-1.4.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: matplotlib>=3.6 in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (2.2.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (11.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (2.32.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (1.14.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from mplsoccer) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.6->mplsoccer) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->mplsoccer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->mplsoccer) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->mplsoccer) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->mplsoccer) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->mplsoccer) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->mplsoccer) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6->mplsoccer) (1.17.0)
Downloading mplsoccer-1.4.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 kB 3.1 MB/s eta 0:00:00
Installing collected packages: mplsoccer
Successfully installed mplsoccer-1.4.0

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from mplsoccer import VerticalPitch

In [ ]:
df = pd.read_csv('erling_haaland_2022_understat.csv')

In [ ]:
df.head()

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,479846,20,MissedShots,0.936,0.503,0.484085,Erling Haaland,a,8260,OpenPlay,2022,Head,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Phil Foden,Cross
1,479847,35,Goal,0.885,0.500,0.761169,Erling Haaland,a,8260,Penalty,2022,LeftFoot,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,NaN,Standard
2,479854,64,Goal,0.864,0.405,0.328053,Erling Haaland,a,8260,OpenPlay,2022,LeftFoot,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Kevin De Bruyne,Throughball
3,479855,69,MissedShots,0.953,0.552,0.526608,Erling Haaland,a,8260,OpenPlay,2022,Head,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Jack Grealish,Chipped
4,479856,75,BlockedShot,0.894,0.710,0.066443,Erling Haaland,a,8260,OpenPlay,2022,LeftFoot,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Ilkay Gündogan,Pass

In [ ]:
df['X'] = df['X'] * 100
df['Y'] = df['Y'] * 100

In [ ]:
df.head()

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,479846,20,MissedShots,93.599998,50.299999,0.484085,Erling Haaland,a,8260,OpenPlay,2022,Head,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Phil Foden,Cross
1,479847,35,Goal,88.500000,50.000000,0.761169,Erling Haaland,a,8260,Penalty,2022,LeftFoot,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,NaN,Standard
2,479854,64,Goal,86.400002,40.500000,0.328053,Erling Haaland,a,8260,OpenPlay,2022,LeftFoot,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Kevin De Bruyne,Throughball
3,479855,69,MissedShots,95.300003,55.200001,0.526608,Erling Haaland,a,8260,OpenPlay,2022,Head,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Jack Grealish,Chipped
4,479856,75,BlockedShot,89.400002,71.000000,0.066443,Erling Haaland,a,8260,OpenPlay,2022,LeftFoot,18211,West Ham,Manchester City,0,2,2022-08-07 15:30:00,Ilkay Gündogan,Pass

In [ ]:
total_shots = df.shape[0]
total_goals = df[df['result'] == 'Goal'].shape[0]
total_xG = df['xG'].sum()
xG_per_shot = total_xG / total_shots
points_average_distance = df['X'].mean()
actual_average_distance= 120 - (df['X'] * 1.2).mean()

In [ ]:
actual_average_distance

np.float64(11.720000401938833)

In [ ]:
background_color = '#0C0D0E'

In [ ]:
import matplotlib.font_manager as font_manager

font_path = 'Arvo-Regular.ttf'
font_props = font_manager.FontProperties(fname=font_path)

In [1]:
fig = plt.figure(figsize = (8,12))
fig.patch.set_facecolor(background_color)

ax1 = fig.add_axes([0,.7,1,.2])
ax1.set_facecolor(background_color)
ax1.set_xlim(0,1)
ax1.set_ylim(0,1)

ax1.text(
    x = .5,
    y = .85,
    s = 'Erling Haaland',
    fontsize = 20,
    fontproperties = font_props,
    fontweight = 'bold',
    color = 'white',
    ha = 'center'
)

ax1.text(
    x = .5,
    y = .75,
    s = 'All shots for Man City in PL 2022-23',
    fontsize = 14,
    fontproperties = font_props,
    fontweight = 'bold',
    color = 'white',
    ha = 'center'
)

ax1.text(
    x = .25,
    y = .5,
    s = 'Low Quality Chance',
    fontsize = 12,
    fontproperties = font_props,
    fontweight = 'bold',
    color = 'white',
    ha = 'center'
)

ax1.text(
    x = .45,
    y = .27,
    s = 'Goal',
    fontsize = 10,
    fontproperties = font_props,
    fontweight = 'bold',
    color = 'white',
    ha = 'right'
)

ax1.text(
    x = .55,
    y = .27,
    s = 'No Goal',
    fontsize = 10,
    fontproperties = font_props,
    fontweight = 'bold',
    color = 'white',
    ha = 'left'
)

ax1.scatter(
    x = .47,
    y = .3,
    s = 100,
    color = 'red',
    edgecolor = 'white',
    linewidth = .8,
    alpha = .6
)

ax1.scatter(
    x = .53,
    y = .3,
    s = 100,
    color = background_color,
    edgecolor = 'white',
    linewidth = .8
)

ax1.scatter(
    x = .37,
    y = .53,
    s = 100,
    color = background_color,
    edgecolor = 'white',
    linewidth = .8
)

ax1.scatter(
    x = .42,
    y = .53,
    s = 200,
    color = background_color,
    edgecolor = 'white',
    linewidth = .8
)

ax1.scatter(
    x = .48,
    y = .53,
    s = 300,
    color = background_color,
    edgecolor = 'white',
    linewidth = .8
)

ax1.scatter(
    x = .54,
    y = .53,
    s = 400,
    color = background_color,
    edgecolor = 'white',
    linewidth = .8
)

ax1.scatter(
    x = .6,
    y = .53,
    s = 500,
    color = background_color,
    edgecolor = 'white',
    linewidth = .8
)

ax1.text(
    x = .75,
    y = .5,
    s = 'High Quality Chance',
    fontsize = 12,
    fontproperties = font_props,
    fontweight = 'bold',
    color = 'white',
    ha = 'center'
)


ax2 = fig.add_axes([.05,.25,.9,.5]),ax2.set_facecolor(background_color)

pitch = VerticalPitch(
    pitch_type= 'opta',
    half=True,
    pitch_color = background_color,
    pad_bottom = .5,
    line_color ='white',
    linewidth = .8,
    axis = True,
    label = True
)

pitch.draw(ax=ax2)

ax2.scatter(x = 90, y = points_average_distance,
            s=100, color = 'white', linewidth = .8)

ax2.plot([90,90], [100, points_average_distance], color = 'white', linewidth=2)

ax2.text(
    x=90, y= points_average_distance - 4,
    s=f'Average Distance\n{actual_average_distance:.1f}yards',
    fontsize=10, fontproperties = font_props,
    color ='white', ha = 'center')

for x in df.to_dict(orient = 'records'):
  pitch.scatter(
      x['X'],
      x['Y'],
      s = 300 * x['xG'],
      color ='red' if x['result'] == 'Goal' else background_color,
      ax=ax2,
      alpha = .7,
      linewidth = .8,
      edgecolor = 'white'
  )


ax3 = fig.add_axes([0,.2,1,.05])
ax3.set_facecolor(background_color)

ax3.text(x=.25, y =.5, s = 'Shots', fontsize = 20, fontproperties = font_props, fontweight = 'bold', color ='white', ha ='left')
ax3.text(x=.25, y=0, s=f'{total_shots}', fontsize=16, font_properties = font_props, color ='red', ha = 'left')

ax3.text(x=.38, y =.5, s = 'Goals', fontsize = 20, fontproperties = font_props, fontweight = 'bold', color ='white', ha ='left')
ax3.text(x=.38, y=0, s=f'{total_goals}', fontsize=16, font_properties = font_props, color ='red', ha = 'left')

ax3.text(x=.53, y =.5, s = 'xG', fontsize = 20, fontproperties = font_props, fontweight = 'bold', color ='white', ha ='left')
ax3.text(x=.53, y=0, s=f'{total_xG:.2f}', fontsize=16, font_properties = font_props, color ='red', ha = 'left')

ax3.text(x=.63, y =.5, s = 'xG per Shot', fontsize = 20, fontproperties = font_props, fontweight = 'bold', color ='white', ha ='left')
ax3.text(x=.63, y=0, s=f'{xG_per_shot:.2f}', fontsize=16, font_properties = font_props, color ='red', ha = 'left')

NameError: name 'plt' is not defined